site_name: FreeFlow Documentation
site_description: The Open Network for EVSE, Carbon Credit Generation, and Contributor Profit Sharing
site_url: https://docs.onfreeflow.com
repo_url: https://github.com/onfreeflow/open-network
repo_name: onfreeflow/open-network
theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - toc.integrate
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: default
    primary: blue
    accent: light blue

nav:
  - Home: index.md
  - Business Plan:
      - Business Plan: business-plan.md
      - Profit Expectations: profit-expectations.md
  - Contributor Resources:
      - Contributor Guide: contributor-guide.md
      - Code of Conduct: code-of-conduct.md
      - Contributor and Partner Agreements: agreements.md
      - Governance: governance.md
      - Brand Usage Guidelines: brand-usage.md
      - Roadmap: roadmap.md
  - Compliance & Legal:
      - Terms of Service: terms-of-service.md
      - Green Programs Policy (CA + US): green-programs-policy-us.md
      - Green Programs Policy (International): green-programs-policy-international.md
      - License: license.md
  - About:
      - Documents Index: documents.md

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - def_list
  - tables
  - abbr
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/onfreeflow
      name: GitHub